### ISSUE TITLE
Not working on dwm 6.3

### ISSUE THREAD

**Issue by shubham-cpp** [aloussase/bliss#2]
So i installed the bar on dwm6.3 but this doesn't showup

This is what I get. Bliss is running I checked with pgrep
![image](https://user-images.githubusercontent.com/31388020/149335983-1cc5ed7a-e112-41c2-b093-202a3361fe78.png)

The patches I have installed

- dwm-actualfullscreen-20211013-cb3f58a.diff
- dwm-adjacenttag-6.2.diff
- dwm-functionalgaps-6.2.diff
- dwm-inplacerotate-6.2.diff
- dwm-restartsig-20180523-6.2.diff
- dwm-switchtotag-6.2.diff
- dwm-systray-20210418-67d76bd.diff

**Comment by shubham-cpp** [comment]
Ok so I removed all patches and installed it on a fresh dwm. It works. Maybe some patch is causing the issue. I'll test and see which patch is causing the issue.

**Comment by shubham-cpp** [comment]
The patch dwmc was causing the issue. I removed that patch and everything works as expected. I had one query does bliss play with  [Awesomebar](https://dwm.suckless.org/patches/awesomebar/) patch

**Comment by aloussase** [comment]
I would assume it does. Though you have to be careful with the size of your bar as they say.

**Comment by shubham-cpp** [comment]
Ok. Not gonna use that patch since my status bar is almost full.
